### ISSUE TITLE
decode/deserialize/parse bytes from mcap ros1msg in rust

### ISSUE THREAD

**Issue by lucasw** [lucasw/ros_one2z#10]
I think I need rosrust for this

**Comment by lucasw** [comment]
https://github.com/adnanademovic/serde_rosmsg

**Comment by lucasw** [comment]
Create simple test bag + mcap

```
rostopic pub /test marti_common_msgs/Float32Stamped  "header:
  seq: 3
  stamp:
    secs: 1
    nsecs: 7
  frame_id: 'test'
value: 1.0" -r 1
```
