### ISSUE TITLE
ros2 mcap record and playback

### ISSUE THREAD

**Issue by lucasw** [lucasw/ros_one2z#8]

**Comment by lucasw** [comment]
```
MAKEFLAGS="-j 4" colcon build --packages-select ros2_example_cpp --cmake-args -DCMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES=$DEST/include
```

**Comment by lucasw** [comment]
How to set qos profile for each topic?  There is metadata in the mcap:

```
      for (const auto& it : reader.channels()) {
        const auto channel = it.second;
        const auto schema = reader.schema(channel->schemaId);
        std::cout << channel->topic << " " << channel->messageEncoding << " "
            << schema->id << " " << schema->name << " " << schema->encoding << "\n";
        // TODO(lucasw) 'reliability' is in here but not sure about the mapping
        for (const auto& m_it : channel->metadata) {
          std::cout << "  " << m_it.first << ": "<< m_it.second << "\n";
        }
...
```

```
/rosout cdr 1 rcl_interfaces/msg/Log ros2msg
  topic_type_hash: RIHS01_e28ce254ca8abc06abf92773b74602cdbf116ed34fbaf294fb9f81da9f318eac
  offered_qos_profiles: - history: 3
  depth: 0
  reliability: 1
  durability: 1
  deadline:
    sec: 9223372036
    nsec: 854775807
  lifespan:
    sec: 10
    nsec: 0
  liveliness: 1
  liveliness_lease_duration:
    sec: 9223372036
    nsec: 854775807
  avoid_ros_namespace_conventions: false
- history: 3
  depth: 0
  reliability: 1
  durability: 1
  deadline:
    sec: 9223372036
    nsec: 854775807
  lifespan:
    sec: 10
    nsec: 0
  liveliness: 1
  liveliness_lease_duration:
    sec: 9223372036
    nsec: 854775807
  avoid_ros_namespace_conventions: false
- history: 3
  depth: 0
  reliability: 1
  durability: 1
  deadline:
    sec: 9223372036
    nsec: 854775807
  lifespan:
    sec: 10
    nsec: 0
  liveliness: 1
  liveliness_lease_duration:
    sec: 9223372036
    nsec: 854775807
  avoid_ros_namespace_conventions: false
- history: 3
  depth: 0
  reliability: 1
  durability: 1
  deadline:
    sec: 9223372036
    nsec: 854775807
  lifespan:
    sec: 10
    nsec: 0
  liveliness: 1
  liveliness_lease_duration:
    sec: 9223372036
    nsec: 854775807
  avoid_ros_namespace_conventions: false
- history: 3
  depth: 0
  reliability: 1
  durability: 1
  deadline:
    sec: 9223372036
    nsec: 854775807
  lifespan:
    sec: 10
    nsec: 0
  liveliness: 1
  liveliness_lease_duration:
    sec: 9223372036
    nsec: 854775807
  avoid_ros_namespace_conventions: false
```
